version: "3.9"
services:
  chat:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8085:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire:18889
      - OTEL_SERVICE_NAME=chat
      - OTEL_SEMCONV_STABILITY_OPT_IN=http
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

