version: "3.9"
services:
  chat:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8085:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_SERVICE_NAME=chat
      - OTEL_SEMCONV_STABILITY_OPT_IN=http
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=True
  aspire:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

